# Generated by Django 4.2.4 on 2023-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nuber',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
